# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='boxart',
            field=models.ImageField(default='games/default.jpg', upload_to='games/'),
        ),
    ]
