# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_game_boxart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='boxart',
            field=models.ImageField(default='games/default.png', upload_to='games/'),
        ),
    ]
