# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20170812_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='boxart',
            field=models.FileField(default='games/default.png', upload_to='games/'),
        ),
    ]
